#!/usr/bin/env ruby

require 'mail'

### ----- configure the email options, gmail for example
options = { :address              => "smtp.gmail.com",
            :port                 => 587,
            :domain               => 'gmail.com',
            :user_name            => 'login',
            :password             => 'password',
            :authentication       => 'plain',
            :enable_starttls_auto => true
}

to_email = "to_email"
from_email = "from_email"
subject = "[Exception][Munin] - #{Time.now}"
body = ""

### ------ cofigure end

Mail.defaults do
  delivery_method :smtp, options
end

for line in $stdin
  body += line
end

Mail.deliver do
  to to_email
  from from_email
  subject subject
  body body
end
